### ISSUE TITLE
Notification spam for ladder

### ISSUE THREAD

**Issue by Rackover** [FAForever/downlords-faf-client#1011]
![image](https://user-images.githubusercontent.com/33836535/48100264-c49a1d80-e222-11e8-9025-4f4512eb5f52.png)

As soon as I have a "Optimal adversary available", i have like 10 notifications at once, and then it disappears. Very annoying as it happens **even ingame**, and when i'm ingame, well i don't really care if someone is available to play.

**Comment by axel1200** [comment]
Also remove notifications when in game if not the case

**Comment by micheljung** [comment]
I regret implementing this notification since the day it was released. I'm not a fan of the status-bar solution, either (that's simply not what a status bar is for), but it's certainly less intrusive.

I wish that we find a better solution, maybe a button in the menu bar. If not, we could fall back to the status bar.

**Comment by Sheikah45** [comment]
Ladder notification removed with tmm
