### ISSUE TITLE
Scroll bar too small

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/downlords-faf-client#1032]
Currently the chat scroll bar is so small its really hard to click, and only possible in fullscreen, else the cursor snaps to the resize function:
![downlords-faf-client_2018-11-13_18-05-36](https://user-images.githubusercontent.com/10947024/48430158-e76e8980-e76e-11e8-9024-50808b9bca08.png)

**Comment by Katharsas** [comment]
Discord has various scrollbar styles depending on which area it scrolls:
- Areas that need to be scrolled often and far have a big scrollbar
- Big scrollbars aren't just big, they capture the mouse in an area at least twice as big as the scrollbar visual
- Big scrollbars don't have a resize separator next to them, so the scrollbar mouse ares does not onflict with a resize area
- Areas that don't need to be scrolled often or barely at all have a smaller scrollbar, but they too do not conflict with resize handlers

Blodirs sketch also features [usable scrollbars](https://forums.faforever.com/viewtopic.php?f=2&t=17342). Some changes for the client that make sense imo:
- Remove resizability of panes where it is not necessary:
  - News list
  - Chat channel user list
  - Tournaments list
- Make scrollbar big for: 
  - All of the above
  - Custom games list/tiles
  - Anything in the Vault
- Scrollbar for Custom games details could stay small because its probably not used much at all and mousewheel should be able to scroll through the entire details very fast. However, scrollspeed needs to be increased massivly for this view, its extremely low.
- Custom games details view currently becomes scrollable horizontally in addition to vertically when the game name is bigger than fits in the windows. This looks bad and adds unnecessary horizontal scrollbar. Just wrap long names.

**Comment by mirddes** [comment]
Currently the chat scroll bar is so small its really hard to click, and only possible in fullscreen, else the cursor snaps to the resize function:

100% agree. did not know i could fullscreen it to avoid the MASSIVE GLARING BUG

**Comment by 1-alex98** [comment]
it is that u drag the client instead of moving the bar, I dont think it is acctually to small. But yes it is an issue

**Comment by mirddes** [comment]
please fix it. scrolling the whole list of active players takes a long time. clicking at the top of the scroll bar to return to the top would be really nice.... a standard feature present in most scroll bars.

**Comment by 1-alex98** [comment]
Well we simply lack man power for many things, you can try fix it yourself if u want to. There are probably ppl on our zulip(chat) which could help u or another option would be put a bounty on this issue: https://issuehunt.io/r/FAForever/downlords-faf-client

**Comment by 1-alex98** [comment]
https://www.youtube.com/watch?v=M0K6UjWnLTc

**Comment by 1-alex98** [comment]
![grafik](https://user-images.githubusercontent.com/19996713/75630611-a06b0880-5bec-11ea-8629-6cd9d6402537.png)

**Comment by mirddes** [comment]
Did you fix it?

**Comment by 1-alex98** [comment]
No I just did it for my self :D just kidding
