### ISSUE TITLE
Don't display all mods in tile view

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#1054]
![image](https://user-images.githubusercontent.com/1864183/48972316-efa8ad80-f027-11e8-8983-06ed96bde5f8.png)

When there are more than 3 mods, it should say "MOD1, MOD2, and N more"

**Comment by tobias-strenger** [comment]
ehm it works for me actually
![image](https://user-images.githubusercontent.com/7430874/50368632-46ec6000-058b-11e9-98a3-419d4749bb52.png)

```Java
if (simModCount > 2) {
    return new SimpleStringProperty(i18n.get("game.mods.twoAndMore", modNames.get(0), 
    modNames.size()));
}
```

Currently it supports only one mod, but i can change it to two. 

I'd rather mention two other issues 
- _N_ doesnt show the correct number of remaining mods (i don't know why the actual number is way bigger, but `(modNames.size() - 1)` because of _n - displayed mods_ would be a start)
- It would also be good to have _Unknown Sim Mods_ only displayed if there are no other known mods used.

**Comment by AlexIzh** [comment]
Also, now a user can't see the list of all modes for a game. Neither inside a tile nor inside right-side info
