### ISSUE TITLE
Show if game is rated

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1062]

**Comment by micheljung** [comment]
While I understand that this is desirable, it's impossible to guarantee that a game will be rated. Best we could say is "there is a chance that it will be rated".
1. The game may get unrated while it is running (e. g. because it ends too early, players agree to draw, game desyncs)
1. Just because the current game settings allow it to be ranked doesn't mean the host won't change the settings before he starts the game
1. Games with uneven teams aren't ranked; so either you join an even "ranked" game, making it unranked, or you join an uneven "unranked" game, making it ranked.

There would be so much forth-and-back, guessing and/or lying in the game "rankiness" that I'm questioning whether it makes sense to even try to implement this.
Finally, only the server knows which game can be ranked and can't, so at most the client should get the information from the server instead of deciding itself.

**Comment by dev-nulled** [comment]
@axel1200 I'd personally ask for the opposite.  If we see something (restrictions, mod type) that show a game is will be unrated, to mark it as such.  Like you mentioned - player rank, etc factors in, but large swaths of games could be ruled out.

**Comment by 1-alex98** [comment]
https://github.com/FAForever/downlords-faf-client/issues/1593
