### ISSUE TITLE
[ Linux ] [ v0.9.3-beta ] Statistics and Achievements are not recorded

### ISSUE THREAD

**Issue by douglasg14b** [FAForever/downlords-faf-client#1103]
Statistics and Achievements do not seem to be recorded on the Linux client.

**Comment by Brutus5000** [comment]
This is done by the server not by the client.

**Comment by douglasg14b** [comment]
@Brutus5000 Where do I create an issue with this then? Since this only happens when using the Linux client, that seems to be a correlation. Isn't the client responsible for sending that information to the server?

Just trying to figure this out, since it's a bit odd.

**Comment by Brutus5000** [comment]
First, there is no dedicated "Linux client". There is the python/legacy client and the Java client. You can run both under Windows and Linux as well, while Linux is still quirky.

Second, the statistics for achievement are taken from the data stream of the Forged Alliance game  process. The FAF client only acts as a relay and forwards the data. If the FAF client relay functionality would be broken, other issues would arise as well (i.e. the ratings would not be updated). As I know that there are a lot of Linux users out there and rating issues are usually detected very fast I do not think that there is a problem in the client.

So this brings me to the following questions:
How did you verify that the achievements are not properly updated? (There might be an issue, but it could also be that this is related due to your games not being rated for reasons like unit restriction, unrated mods etc)
How did you verify that the issue only happens on Linux?
