### ISSUE TITLE
[ Linux ] accepting ideas for .desktop launcher

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1126]
I've tried everything. 

any suggestions for getting an ubunu/debian desktop launcher working?

these are .desktop files with this sort of format : 

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Type=Application
Terminal=true
Exec=bash -i 'cd faf && ./downlords-faf-client'
Name=FAF
Comment=Forged Alliance Forever Client
Icon=/home/t/.local/share/icons/faf.png
```

it should work but does not. it and just about 200 other variants I've tried.

java FAF is the one and only app that has eluded gui-launch for over a year now.

**Comment by TheBlueTroll** [comment]
i just chucked all the stuff in my run.sh into a desktop launcher, and got this that runs

```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=true
Exec=bash -c "cd /home/jason/faf/downlords-faf-client-0.9.4-beta;export INSTALL4J_JAVA_HOME=/usr/lib/jvm/default-java/; ./downlords-faf-client"
Name=FAF
Comment=Forged Alliance Forever Client
Icon=/home/jason/.local/share/icons/faf.png
```

dunno bout the icon bit, but otherwise that runs for me, just had to make sure a java 10 compatible jre was installed and that the folder was right. works on linux mint 19.1 cinnamon, but i dont see why not on ubuntu as well. good luck.

**Comment by tatsujb** [comment]
@TheBlueTroll you get a golden cookie! congrats! use it wisely!
