### ISSUE TITLE
Avast IDP.Generic false positive on client

### ISSUE THREAD

**Issue by mantis** [FAForever/downlords-faf-client#1204]
hi Guys, 

Just as FYI - have reported to Avast that Avast is picking up that faf client application as IDP.Generic today as a possible false positive.

Thanks

**Comment by 1-alex98** [comment]
Do you have an option in your avast to tell it you trust it :D Some anti-viruses have that option and if enough ppl do so they will reconsider

**Comment by mantis** [comment]
I submitted it for review through their UI + added an exception for the FAF install path - it was for a friend. Thought i'd mentioned it here  in case it helps others.

**Comment by 1-alex98** [comment]
We still ship, but don't use it atm, because it is not needed since we enforce steam link, the uid.exe. It is an closed source executable that reads out tings like cpu name, os version, wifi- card mac address to determine a unique id. So that it got hard to have multiple accounts and smurf. As we know have steam linking the check is actually deactivated, but anti-viruses sometimes trigger on it. Probably because it uses specific system functionality that also malicious programs use....

**Comment by 1-alex98** [comment]
I also made a report to avast that points to this very GitHub issue.

**Comment by 1-alex98** [comment]
Did it say which file in particular it complains about?

**Comment by mantis** [comment]
it was complaining about the downlords-faf-client.exe itself, and the installer

**Comment by 1-alex98** [comment]
hmm ok strange, well the uid.exe is incorporated in it somehow, but yeah it is probably also compressed so yeah strange.
