### ISSUE TITLE
1v1 Ranked Match - FA client gets stuck on "Setting up automatch" indefinitely.

### ISSUE THREAD

**Issue by RoraRaven** [FAForever/downlords-faf-client#1206]
When a match is found, the FA client starts up, then goes to the "Setting up automatch" screen, and stays there, forever.

No issues with custom games. Ports are open in the firewall.

Logs attached.
[downlords-faf-client.log.2019-05-06.0.gz](https://github.com/FAForever/downlords-faf-client/files/3150128/downlords-faf-client.log.2019-05-06.0.gz)
[forever.log](https://github.com/FAForever/downlords-faf-client/files/3150129/forever.log)
[forever.log1.txt](https://github.com/FAForever/downlords-faf-client/files/3150134/forever.log1.txt)

**Comment by 1-alex98** [comment]
forever.log is the py client log

**Comment by Askaholic** [comment]
I‘ve already implemented server messages that inform the client when the host fails to start a ladder match within a few minutes. I will add this for the guest as well eventually. The client could look at these messages and kill the running game instance. Also if you have a better name for the messages let me know, now would be an easy time to change them since they aren’t being read yet. 

See server `ladder_service.py`

**Comment by 1-alex98** [comment]
outdated
