### ISSUE TITLE
Remember used mods / add select previous mods button

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1230]

**Comment by 1-alex98** [comment]
That should be done already

**Comment by 1-alex98** [comment]
This bug happens when the mods are installed in the ProgrammData directory for mods, which was used by the py cleint. The mods can not be found in the client so the client deactivates them every time a player plays a game. When setting them to activated in the game the change is later overwritten by the client...

**Comment by Sheikah45** [comment]
Should be fixed with optional use of FallbackVault Location
