### ISSUE TITLE
Debrand the client

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1233]
This client is now the official faf client. There's no reason anymore like there was in the first place to integrate a player's username into the client name. Technically that will probably stay, but a lot of users are confused by the client's name.

**Comment by 1-alex98** [comment]
Lets call it after the main developer atm 😈

**Comment by Brutus5000** [comment]
This is not a beginner friendly task. It is much more than the launch screen

- How should we deal with the installation path? Install4j might run into problems if we change it. 
- All preferences might get lost.
- Should we rename the git repo? Which workflows will break due to that? (e.g. translations)

**Comment by 1-alex98** [comment]
Yes not beginner friendlly

**Comment by micheljung** [comment]
When I started, I called it "FAF 2.0" but I was asked to change the name. Now we have the salad 😜

**Comment by 1-alex98** [comment]
Is that something u can say in English? Or is it like "the yellow from the egg"....?

Update: turns out that is nothing u could say in English. Would be "Now we are in a right mess".

**Comment by Sheikah45** [comment]
Closed with #2379
