### ISSUE TITLE
Coop Tab Issues & UI layout

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#1266]
- Make game list more readable. I should be able to do this. Related: #803 

This is how it currently looks for me (fullscreen):
![fafclient_coop](https://user-images.githubusercontent.com/1922573/58115987-8df28600-7bfb-11e9-8fb3-71d37341a07b.JPG)

Todo:
- Remove "Maps" and "Rating" column
- Give the table more space by moving the split to the left (its not adjustable by user)

Tell me if you are fine with that.

**Comment by Katharsas** [comment]
The leaderbords should be moved to the leaderbords tab

---
The "Custom Games" settings like "Show private games" are buggy (they kind of affect the coop games list, but not fully working). Imo, the coop games list and custom games list should be merged. I don't see a reason for keeping them separate:
  - They are not really separate anyway because custom games list settings affect coop games list and coop tab does not have its own settings.
  - We get a tiles view for coop games as well
  - Less UI duplication
  - Allows people to see all custom games in one list without having to switch
  - It makes sense to have "Create custom game" and "Create campaign game" near each other or even in the same dialog. Currently, we have "Create game" vs "Host game", i dont see a reason for this inconsistency.

I suggest havinga single list with two segments that are clearly separated or two lists below each other that share column/row size, alignment and settings. 

---
"Co-Op" as a description for Campaign and Missions doesn't make sense.
  - It should be inherently clear anyway that the campaign can be played as coop because 1. there is a list of campaign games that you can see & join and 2. when you "host" a coop game, a lobby with multiple player slots opens and your game appears in the list. So there is no need to call these "Co-Op"
  - It is possible to play survival coop games or Co-Op against AI in the custom games tab.
  - The Co-Op tab is more about playing story/campaign missions or user-made missions or in the future  tutorials than about coop

**Comment by Katharsas** [comment]
Closing this as i don't have time to implement it currently. Might reopen later.

**Comment by Askaholic** [comment]
I actually like to have the leaderboard on the same page because it can give you an estimate of how long the mission might take to complete. What if we split the UI up into two modes: Joining and Browsing. 

So when you first load up the coop tab it starts in the "joining" mode where it shows you all the games that are available. Somewhere on the page there is a "Browse Missions" button which when you click it reveals the mission list and leaderboard. From this browse view you can also host a mission.

Something along those lines so that the tab doesn't need to squeeze everything on the same screen all the time.
