### ISSUE TITLE
"M&M Top Picks" Vault Category

### ISSUE THREAD

**Issue by CouncillorMorax** [FAForever/downlords-faf-client#1282]
![layout image](https://user-images.githubusercontent.com/23299209/59161187-70536680-8aad-11e9-8343-abf10686c8ad.jpg)

In the vault section of the Java client, a new category in the maps and mods vault will be added which reads a list of map or mod IDs, generated by the M&M team.

The list will live on the message board and through a shared file (link to be added soon(tm)).

No modifications to the GUI are needed and should look like the rest so there is a good flow.

Once the permission system is restored to the java client, the map and mod id list will exist solely as a source of reference. The team can then use their mod access to create the list from within the client rather need to request updates to the moderation team.

**Comment by 1-alex98** [comment]
Just one note to this. This is an open source project and developers do what they want (you are soon to realize). I just want you to understand that just because you are councilor your suggestions will not be realized. Maybe I read them a little closer than those from a random user but thats it then basically. And as of now I got a lot to do and this requires some changes. So for me this has relatively low priority.

If you wanna get the things done you desire you best search yourself a dev and convince him of your idea. Or you can make some advertisement for us to get more devs ;)
