### ISSUE TITLE
Emphasize generate map button

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1321]
The generate map button is nearly invisible, maybe we should somehow highlight it, e.g. add a "new" tag to it, a generated map logo or change the color.

**Comment by Katharsas** [comment]
Mockup suggestion:
![map_generator_mockup](https://user-images.githubusercontent.com/1922573/65345164-e5205b80-dbd9-11e9-8586-755b33a74b16.PNG)

The idea is that the position under the map list is bad, becasue intuitivly people will expect these buttons to manipulate the list.  And there is not enough space there to have a NEW label in the button.

I just chose the colors for the button randomly, if you want to reserve white for Create button only, we could also think about making the button turquoise, the NEW label background and "genrate map" font white, and the NEW font dark grey.

**Comment by Rackover** [comment]
**do not put new buttons above information**

if i remember correctly one of the keypoints of the faf java client over the python client is to have a proper ui design. Adding buttons in random places without questioning it further is going in the wrongest of directions

there's a place for buttons and you can see it clearly => the bottom of that window (that "window" should not even exist in material design but eh)

Reorganize the current buttons, change their size, color if you want, but do not put them somewhere else in the window if it doesn't make any sense. The problem is that you guys have an orgy of useless button on that window.

**Here's an idea of reorganization:**
![image](https://user-images.githubusercontent.com/33836535/65346599-aea70880-dbfa-11e9-9b71-d3b0df993777.png)
Remove that "Reload" button and instead reload the mod list each time the player is trying to host a new game

![image](https://user-images.githubusercontent.com/33836535/65346613-b9619d80-dbfa-11e9-93c1-93b1ec1bbc4f.png)
Remove that button and instead rename FAF to "FAF (default)" in the list

![image](https://user-images.githubusercontent.com/33836535/65346642-caaaaa00-dbfa-11e9-9e02-b775f61a64f1.png)
This Cancel button is wrongly placed because it's extremely close to another button that does the exact opposite... Put the cancel button in the bottom left corner


You now have only 3 buttons left in your "important" space. Random map, generate map, host game. so you can resize them the way you feel fit without making a mess.

**Even better:**
Make "generate map" a tick box ( generate map when the player hits" create" rather than on clicking the button ), placed above the map list (it's not a button so you can put it here). The checkbox is ticked by default and when it's ticked, the list of maps is greyed out.

You even gain space because a tickbox takes less space than a button, so you can keep your list at the original size

**Comment by Katharsas** [comment]
Summary of Zulip discussion:
- Remove "Select default" as described by Rackover
- Move Cancel button there instead and left align as described (maybe add margin above for better separation from list?)
- Put "generate map" button either below "random map" button or above "Create" button (test it and check how busy the space below the image preview usually is or can get)
- Try turquoise background color scheme for "Generate map" button.
