### ISSUE TITLE
new "Reset Settings" function does nothing

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1356]
![Screenshot from 2019-07-21 12-13-27](https://user-images.githubusercontent.com/5132359/61589908-0e5c4580-abb1-11e9-8022-5b1c2279a784.png)

this function fails to do what it's text implies it would do. 

clients.pref files being missing will erroneously trigger this window instead of just writing new clients.pref

pressing the "Yes" button in this prompt in a case where clients.pref is missing will result in nothing happening and FAF client being permanently unable to init until the `.faforever` folder is deleted entirely correctly triggering a total recreation of this folder including client.prefs

**Comment by 1-alex98** [comment]
First:
Asking the user is needed some might wanna backup their settings...
Second:
The button is gonna delete the client.prefs file that is intended like that. The functionality would be too much some ppl would need to redownload coop etc.

Could u send me the log of this happening? I mean u said the client.prefs are missing anyway... So the prompt is simply wrong... I would assume it is some permission error that the client can not read or write the none existing client.prefs file and instead of showing that error it shows this prompt

**Comment by tatsujb** [comment]
yeah I'll get you a log when I get home tonight.

it's not supposed to currently be possible for the client to be stuck in an infinite init loop like it is if client.prefs is the only file missing, right? 

I mean I don't think this is intended behavior.

**Comment by 1-alex98** [comment]
Well if it is missing it is created

**Comment by 1-alex98** [comment]
And when I should guess what happens in your case is that the client is unable to create it

**Comment by Sheikah45** [comment]
Most likely user permissions error
