### ISSUE TITLE
Tests: JavaFX Toolkit state is not cleaned up after test class

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#1387]
How to reproduce:
- Create new package `mypackage` with these 2 new test classes:
```
public class A extends AbstractPlainJavaFxTest {
  @Test
  public void test() {
    assertTrue(true);
    WaitForAsyncUtils.waitForFxEvents();
  }
}
```
```
public class B {
  @Test
  public void test() {
    assertTrue(true);
    WaitForAsyncUtils.waitForFxEvents();
  }
}
```
- Run entire package, for example `gradle test --tests com.faforever.client.mypackage.*`
  -> Both tests will succeed
- Run ONLY test class `B`
  -> Test will fail because it is missing parent class `AbstractPlainJavaFxTest ` for JavaFX toolkit initialization

`AbstractPlainJavaFxTest` is "leaking" the toolkit initialization into other classes.

**Comment by 1-alex98** [comment]
Hmm no idea

**Comment by Katharsas** [comment]
There is a chance maybe that its fixed if we change to a new version of JavaFX / TextFX. Other than that we would have to look into TextFx ourselves.

**Comment by Sheikah45** [comment]
I believe this issue is because the application persists for the entire execution. JavaFx does not allow you to have two applications running at once as you cannot call the launch method twice in the same session. TestFx sets the application so that it won't close when all the windows are closed so that it continues to run for the entire session.

I do not believe there is a way to get around this behavior.
