### ISSUE TITLE
Offer prefix search

### ISSUE THREAD

**Issue by norraxx** [FAForever/downlords-faf-client#1402]
Add "Starts with" criteria in vault for searching.
Place it at first place above "Contains".

Reason: lower database load.

**Comment by Katharsas** [comment]
The proper solution ~~would~~ could be a text search db like ElasticSearch, but i guess that is overkill...

**Comment by norraxx** [comment]
Yes, you are right, but we won't add another technology to faf, because we're lacking the man power.

**Comment by Brutus5000** [comment]
Apart from what norraxx already stated I don't see how throwing \<yet another hyped technology X> onto our stack magically integrates with our existing applications / frameworks.
So no it's not a "proper" solution. Without an actual concept it's just a buzzword.

**Comment by Katharsas** [comment]
Hyped? Elasticsearch is an almost boring standard solution for text search (its THE most popular OS solution), and its not that hard to utilize. But since i don't want to maintain sync to an additional db and you probably don't as well, it is, as i stated, overkill.

Its definitely not a buzzword though, ive used it and it works fine. Basically every open source stack that allows you to search for text in more advanced ways (like centralized log search, check out ELK stack) uses it.

So yes it would be the ~~"proper", low risk, default option~~ default technology.

**Comment by norraxx** [comment]
First of all: 
- there is no magic and we should to do more job, than we now imagine.
For example we should to have the way to synchronize data between databases, otherwise our integrity will fail, and we will show invalid results. It brings us some sort of queues + code.
- We don't have man capacity, (I don't have my capacity for faf, sorry)
- It was first thing that I've offered, but... see line above.

And YES! Lucene, or wrapper on Lucene called - Elasticsearch would solve fulltext problems - yes, but not other problems like: fulltext word + join on 4 tables ordered by 4th one.

**Comment by Katharsas** [comment]
Yeah its not as easy as "install ES and it magically works". Maybe at some point in the far future.

**Comment by 1-alex98** [comment]
add a start inform and make search for IS
