### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by SamuelBadr** [FAForever/downlords-faf-client#1404]
On startup, I get the splash screen for a few seconds and afterwards this error:

https://gist.github.com/Samuel3008/fc36246f9c1609ec835d5acbde65c2a4

What I tried:

- This is on a fresh installation of Windows 10 (I literally did not install anything but Steam and SupCom FA beforehand).
- I do not have a `%appdata%\Forged Alliance Forever` folder.

There are many issues like mine, but all solutions involve deleting some `.prefs` file(s) and it seems I don't have any of those.

**Comment by Katharsas** [comment]
The client crashes with "Access is denied." exception in this line:
`GPG_FA_PATH = Paths.get(Shell32Util.getFolderPath(ShlObj.CSIDL_PERSONAL), "My Games", "Gas Powered Games", "Supreme Commander Forged Alliance");`

This means it doesn't have the rights to or is otherwise prevented by your system from accessing
`C:\Users\<user>\Documents\my games\Gas Powered Games\Supreme Commander Forged Alliance`

**Comment by SamuelBadr** [comment]
This did it, thank you!

I'm running Windows inside of a VM (Parallels Desktop) which automatically shares the host user folder (`~`) with Windows'. Turning that off allowed the client to start normally.
