### ISSUE TITLE
Ability to watch replays while waiting in lobby

### ISSUE THREAD

**Issue by andreasley** [FAForever/downlords-faf-client#1523]
A common pastime while waiting for a lobby to fill is watching replays. 
Unfortunately, the client currently allows only one FA processes to run at a time.

In theory, there's nothing preventing the client from launching multiple instances of FA.
However, some care has to be taken to ensure game binaries aren't being mixed up.

Implementation ideas:
- limit to one replay and one live game at a time
- pause/kill running replay when a live game starts (to prevent any impact on performance)
- if possible, a badge if some kind on the FA icon in the taskbar would be great (to indicate if that app is running a replay)

**Comment by Brutus5000** [comment]
I don't think I want to see this feature in the codebase as the complexity added to the codebase will be really high. (Double patch state management, double process state management, double logging, double error sources).

The file management had and still has issues, putting a second layer on top of it makes it worse. E.g.
https://github.com/FAForever/downlords-faf-client/issues/1352 https://github.com/FAForever/downlords-faf-client/issues/1345 https://github.com/FAForever/downlords-faf-client/issues/1344 https://github.com/FAForever/downlords-faf-client/issues/1251

**Comment by andreasley** [comment]
> I don't think I want to see this feature in the codebase as the complexity added to the codebase will be really high.

If that's the case, then something else is wrong and should be fixed, which I don't mind taking a look at. But that shouldn't discourage from implementing important new features.

**Comment by Brutus5000** [comment]
That's a question of priorities. We have a limited amount of time to use and the question is, do we rather have a client with a limited feature set but few bugs or an expanding feature set with many bugs. I personally prefer the first option.

And especially game launching touches parts of the application that are vastly out of our hands. Users do have issues with file permissions due to os permission or anti virus, but the come to us and complain about it and there is nothing you can do inside the JVM to even give a hint about the cause. Same applies on launching game processes. Do we know how good two game instances can coexist? It may work on some machines, but that doesn't mean it works on all machines. Maybe it only works in non-fullscreen mode or whatever. There are dozens of reason why this feature will cause a lot of trouble and take a lot of support resources.

And it's clearly not an important feature. Afaik it wasn't even mentioned on the list of user wishes in the last survey (and there was tons of other stuff in there).

**Comment by andreasley** [comment]
> That's a question of priorities. 

I completely understand where you're coming from.

At the same time, my motivation for contributing code to this project is mostly personal. I want to work on stuff that I, as a FAF user/player, want to see. I don't mind putting in a considerable number of hours for fixes and features that benefit everyone or that you and other devs consider important, but if there's no room for features like this one, then I'd rather invest my time in other projects.

My suggestion would be to instead set expectations regarding stability, compatibility, performance and – most importantly – define feature ownership/responsibility.

If it turns out that this feature is not worthwhile or too technically complex, I don't mind discarding the idea, but from my current point of view, this isn't the case.

**Comment by 1-alex98** [comment]
Yeah I mean what if the current game is phantom x and the replay is coop... You know allowing this will really fuck up thing not only patching. I would advise against it. Because it will cause some funny cases which nobody ever thought about

**Comment by 1-alex98** [comment]
And as Brutus pointed out the two instances blocking each other(tho that is fixable), i think have two patches at the same is not possible (without changing a lot of stuff) and also hinders us ever building in the new patcher...
You can see if u build some workaround for u  personally but I would speak against official support
