### ISSUE TITLE
migrate map rating/review 

### ISSUE THREAD

**Issue by badbwoi** [FAForever/downlords-faf-client#1581]
Hello,
I was wondering why the map rating/review is not migrated when u upload a new map version?
![image](https://user-images.githubusercontent.com/28671151/74099631-1d431f00-4b26-11ea-928f-8f4d8fcc38db.png)

@axel1200:
> It is not a bug because it was intended on the other hand it is suboptimal i guess

Are there any problem I can't see? Because it would be very nice if the map rating/review could be migrated.

**Comment by Brutus5000** [comment]
This is a difficult topic with no obvious solution.

Why is there a new version? Because something was changed. Usually bugs fixed or quality improved. Thus old comments may get outdated due to this. Do you want to see comments of an outdated version while the points mentioned there are already fixed? (Same applies for the calculated 5-star rating btw.)

So the best way would be to show all comments, but make a badge on comments to older version that this commented belongs to an older version.

**Comment by bukajsytlos** [comment]
imho this is the solution, same as playstore as far as I remember

**Comment by badbwoi** [comment]
I like Brutus idea as well, sounds like a lovely solution.

**Comment by micheljung** [comment]
@Brutus5000 when I designed the reviews, I had this issue in mind and I'm pretty sure the API, at least the database, is able to provide both, reviews per version as well as aggregated ones?

**Comment by 1-alex98** [comment]
And again it is not a client issue right?
