### ISSUE TITLE
Changing the system time breaks ladder queue timer

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1622]

**Comment by Sheikah45** [comment]
I think this requires additional information from the server. Currently we only know what time the queue is supposed to pop. If the server time and the system time are not aligned there is no way to correct the timer since we don't know when the server sent the message in relation to the queue pop time without the systems being aligned

**Comment by Sheikah45** [comment]
Hmm even with more information I am not sure this can be avoided unless we assume the server message arrived nearly instantly

**Comment by Sheikah45** [comment]
Would need a server and client change and most likely wont happen
