### ISSUE TITLE
Improve chat readability

### ISSUE THREAD

**Issue by FemtoZetta** [FAForever/downlords-faf-client#1651]
Make the chat easier to read. Using the Python client, a few easy suggestions that would already help a lot:
-make the names/clan/flag right aligned
-add ":" after the name, before the message

Example to show that it does make it easier to visually match names with messages:
Python:
![grafik](https://user-images.githubusercontent.com/61892809/77867233-f51e9500-7225-11ea-972f-6d1204568a0a.png)
Java:
![grafik](https://user-images.githubusercontent.com/61892809/77867251-04054780-7226-11ea-9da8-3e80d92634bc.png)

**Comment by Blodir** [comment]
Feedback/suggestions:
* Remove the flags: they are redundant (this info can be seen elsewhere and it only needs to be checked rarely, not important enough to be shown next to each message) and call for too much attention (taking away from the actual content)
* Adjust username font-weight (remove bold): username is calling too much attention to itself distracting from what's important (the actual message), also avatars can already be used to visually identify users which furthermore diminishes importance of the username in visual hierarchy
* Cut off usernames that are too long so that message content always lines up

**Comment by Katharsas** [comment]
I think the username is much easier to tell apart from the message in Java client than in python client (thanks to being bold, space between clan and name, no colon, message position is aligned more often). I don't agree that it takes too much attention, i think that is a matter of being used to it or not.

I think Java client looks kinda bad because the distance between name and message is quite big sometimes, so it creates a visual disconnect.

An alternative suggestion:
Give every second message a slightly different grey background (css: even/odd) so that you end up with rows that are easy to see. The python client kinda prevented the visual disconnect with the coloring of the text and by putting name and message close together (which is imo the only reason it needs the ugly colon in the first place).

In general:
Whenever there is a discussion about visual style, a bunch of people tend to show up that claim that the python client looks better in every little detail and want to bring that exact style to the Java client. People like what they are used to (which is why there is always complaints when any software in the world changes its style here and there).
So please keep in mind that a lot of people use the Java client and are used to how it looks right now. Any style changes should really have a good argument why the readability is improved (and "i just think it looks better" is not a valid argument).
And taking a look at how other software solves this problem before changing style (and thinking if we can use that for us) is always a good idea as well.

An you can bet that a ton of people will complain once it is released about any changes whatsoever (no matter if they are good or not), so have a good reason ready.

**Comment by BlackYps** [comment]
bold vs normal plus colon is debatable and probably down to what you are used to seeing. But right aligned user name is important to not have these big gaps with short user names. Avatar (and flag if you want to keep it) should probably stay left aligned to create a clean visual border to the left of the client.
Different background for rows could be nice but I don't consider it as an alternative. More like a possible extra.
Also it would be really nice if the timestamp only shows when the time incremented.
Also thumbs up from me for username cutoff
