### ISSUE TITLE
Auto update mods

### ISSUE THREAD

**Issue by RK4000** [FAForever/downlords-faf-client#1680]
As the title says, maybe a feature that would automatically update mods would be nice.

If someone for example tries to host a game, with V2 of a certain mod, but V5 is the latest, the client should recognise V2 as hidden in the vault (maybe just a simple name-check, since that's how automatically hiding old versions works already?), and auto-download the latest version before the game launches. 

This would reduce the hassle for mod users, while also preventing the old versions from circulating after they have been updated. (as they are no longer obtainable from the vault anyway)

**Comment by Brutus5000** [comment]
This is a very complex topic with different layers of problems.

1. We have people with very limited internet connections (bandwith and total limits). Those people won't be happy about auto-updating larger mods (think about blackops for example, that is 300mb), especially if they just play against AI or friends. 
2. Mods in game are handled completely different than mods in FAF client. Afaik the game just scrapes everything in the mod folder and lists it. From the games perspective there is no such thing as a version or a hidden flag (there is a blacklist, but that can only be updated with game patches and I don't know how it works exactly). The FAF client can query our API and knows about hidden stuff and newer version. The connection between client and game is the filename. 
- What we can control is which mods we show in the create game dialog in the FAF client. However what is shown in the game is based on what the user has on disk. So if the user starts a game without mods and then selects them in the ingame lobby we wouldn't notice. 
- The alternative would be to update all mods before launching the game, which is problematic because of point 1. Also this still doesn't solve what shows up ingame.
- So the client would need to delete older mods from disk to not have them show up in the game anymore. But for replays you might still need these files. So deleting them is not an option.
4. Backwards compatibility: If a newer version is broken or incompatible with another mods, there would be no way to get it back, as it would be auto-updated. I don't know if this is a common issue in FAF.

So the question is what would be the best solution? I don't know.
Potential ideas:
- Make available updates on mods appear in the notification screen.
- Move outdated mods in a dedicated directory and mount them only in the init.lua on playing replays (not sure if this is possible and/or requires code changes in the game)

**Comment by tatsujb** [comment]
I like your last idea.

I think for point 1 we could add an option in the settings : "slow internet"

otherwise mod update is default.

And yeah "updates" would consist of FAF moving all outdated mods to folders that FA doesn't "scrape".

as for point 4 I guess the right choice would be to make the mod dependency chain outdated as a whole : the responsibility has to go back to the mod maintainers. FAF client can't be expected to be responsible for that.

I think with such a setup we would have be the best of all worlds. 

It would however have the "downside" of requiring more rigor from the modders

**Comment by 1-alex98** [comment]
I will only check on mods that are actually selected in the current game. Nobody should be playing outdated mods. If your connection is slow you should not play mods... Also mods normally do not change to frequently

**Comment by Sheikah45** [comment]
Haha well you should check the recent mod uploads there are some hefty mods that get at least weekly updates

**Comment by 1-alex98** [comment]
Well if you plays those mods that's on you then I guess

**Comment by 1-alex98** [comment]
Or the contributors need to change their behaviour.
