### ISSUE TITLE
Layout issue in online replays

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#1766]
**Describe the bug**
The random faction icon (?) in the Line-Up seems to have a different margin then the other faction icons.

**To Reproduce**
Open the replays in the online replay vault.

**Expected behavior**
All users have the same space between them

**Screenshots**
Replay id #9621034
![image](https://user-images.githubusercontent.com/6843462/84375202-7fe51e00-abdf-11ea-93eb-5de537cc2354.png)

Replay id #10678526
![image](https://user-images.githubusercontent.com/6843462/84375284-9ee3b000-abdf-11ea-99c3-4ac4d20d6f77.png)

**OS**
Linux (javafx 11 and 14)

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Askaholic** [comment]
It's because the random faction thing is an image and not a text character like the others. The reason is that it needs to have multiple colors, and coloring a single character with multiple colors is non-trivial. Might be able to do it with some custom text effect though. Effects let you do all sorts of crazy things: https://docs.oracle.com/javafx/2/text/jfxpub-text.htm

**Comment by Brutus5000** [comment]
I thought just define a height that covers all cases
