### ISSUE TITLE
[ Linux ] [ v1.1.9 ] Replay links and files don't open

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1841]
**Describe the bug**
Opening replays from any tab in replay vault works but opening replay files and links does not.

**To Reproduce**
open a replay link on linux

**Expected behavior**
I expect the replay to launch 

**OS**
Linux

**Comment by tatsujb** [comment]
With the watch button today it worked. 

there's a somewhat unreliable characteristic to this bug.

**Comment by tneo** [comment]
I have the same issue and this is due to the client downloading the ForgedAlliance.exe file and that can't be executed under Linux.

`2020-09-09 10:46:29.567  INFO 3774 --- [ol-3-thread-167] c.f.c.patch.GameBinariesUpdateTaskImpl   : Updating binaries to 3714`

`2020-09-09 10:46:29.590  INFO 3774 --- [lication Thread] c.f.client.fa.ForgedAllianceService      : Starting Forged Alliance with command: [/home/user/.faforever/bin/ForgedAlliance.exe, /init, init.lua, /nobugreport, /log, /home/user/.faforever/logs/replay.log, /replay, gpgnet://lobby.faforever.com/12605750/user.scfareplay, /replayid, 12605750] in directory: /home/user/.faforever/bin
/home/user/.faforever/bin/ForgedAlliance.exe: /home/user/.faforever/bin/ForgedAlliance.exe: cannot execute binary file`

`2020-09-09 10:46:29.599  INFO 3774 --- [ol-3-thread-167] com.faforever.client.game.GameService    : Forged Alliance terminated with exit code 126`

**Comment by tatsujb** [comment]
well it could if it ran that binary with the same argument we gave it under "Command Line Format for Executable" in our settings :

E.G. I put /home/t/faf/run %s where run is the file generated by steam's proton that has the corrects proton paths ect. 

this is probably a simple case of the if case that was added for linux not being applied in this specific instance, nice catch!

**Comment by Sheikah45** [comment]
stale
