### ISSUE TITLE
Rename default shortcut for client

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#1939]
The shortcut created by the installer is named "Downlord'sFafClient" by default. And changing it in the installer only changes the name of the folder it is put in. The only way is to edit it manually. Which I do, and rename it to "Downlord's FAF Client" cause Windows search has a hard time with it being all one word.

Taken from https://forum.faforever.com/topic/294/rename-default-shortcut-for-client

**Comment by Atrocyte** [comment]
Hey guys, the exact shortcut name is "DownlordsFafClient" (without the quote) and can be found on line 27 of _downlords-faf-client.install4j_
Before rushing to write a pull request I'd like to ask:

1. Should the shortcut name become "Downlord's FAF Client" as stated in the forum post? (I was used to run the FAForever client a while ago)

2. Since this is a suggestion, should this pull request go on a feature or a bugfix branch?

**Comment by 1-alex98** [comment]
@Atrocyte  go with feature. Since we are gradually renaming it maybe maybe go with FAF Client
See  https://github.com/FAForever/downlords-faf-client/pull/1953/files

**Comment by 1-alex98** [comment]
If you want to contribute to FAF in general we can invite you to Zulip(chat service)

**Comment by Atrocyte** [comment]
@axel1200 I would be happy to join you guys in Zulip! I'm looking out for the invite 😃

**Comment by 1-alex98** [comment]
Write me an email alexander.von.trostorff@gmail.com
