### ISSUE TITLE
Foe Issues

### ISSUE THREAD

**Issue by FtXCommando** [FAForever/downlords-faf-client#1985]
This is both a bug and a feature request I guess. The first is that the java client does not seem to allow you to foe users that are "chat only" meaning that irc users are pretty much immune to it. The second is that when you have in fact foed people, they are still able to ping you by saying your name in aeolus. It would be great if that could be removed as part of the reason at least I foe people is when they spam ping me for needless reasons.

**Comment by Brutus5000** [comment]
Please split your issues into dedicated ones. You described 2 different things and they probably won't be fixed by the same pull request.

Chat only users have FAF id and therefore don't fit into the friends & foes system of the server. Furthermore chat only users have no unique identifier (hostname changes, ip changes, username changes). The client could manage a dedicated list of foed chat users, but that would be only temporary on disk. I don't like having the foe feature split up into one part server managed and the other part locally managed.

**Comment by Sheikah45** [comment]
Should people who aren't players be allowed to ping others in aeolus?

**Comment by Sheikah45** [comment]
Not able to foe chat only users through server
