### ISSUE TITLE
[SUGGESTION] Including dependencies manually rather than shading them

### ISSUE THREAD

**Issue by MichaelGatesDev** [FAForever/downlords-faf-client#210]
The repo is including a large amount of files which are unnecessary to have the source code visible for as they're already visible on their original repositories. 

I'd recommend using a plugin like [Shadow](https://github.com/johnrengelman/shadow) or switch the project over to Maven which will be better in the long run in my opinion.

**Comment by micheljung** [comment]
Hi and thanks for your input.

However I'm not sure what exactly you mean by unnecessary files, and how Maven would be better than Gradle in the long run, when the whole world is shifting away from Maven towards Gradle.

**Comment by MichaelGatesDev** [comment]
What I mean is that it looks like you've just cut and pasted packages from existing projects for easy local use within your project scope, however you really should be shading them into the binary when they're actually going to be used. It's cluttering the project structure and is generally a big no-no. 

If you're referring to Android leading Gradle to greatness, you're right. Beyond that, Gradle will do you no good on a project like this. Maven will keep your project organized, understandable, and you will find better support. I don't understand an actual reason to be using Gradle for a JavaFX project. If you were building multiple submodules which required something specific, I could understand.

**Comment by micheljung** [comment]
I copied exactly 6 files into the repo, I don't consider this "a large amount of files" :-)
I know it's a no-go and I absolutely try to avoid, but jbsdiff wasn't available in Maven central that time (I saw it's available now, since Feb. 2016) and `ComparableVersion.java` is really all I needed from `maven-artifact`, so including the whole artifact just for that one class seemed a bit wasteful (granted, as I check it now, it would only be 54KB). If the Shadow plugin helps solving that, I'd be happy to use it (But I was going to use Proguard to shrink the JAR anyway).

However, Gradle absolutely fits this project and keeps it just as organized as Maven would - which is unsurprising, since Gradle combines the strengths of Maven and other build tools while avoiding their weaknesses. I know the strengths and weaknesses of Maven very well since I've worked on a daily basis for about 4 years and developed several Maven plugins.
Support for Gradle is very good - from Documentation, over plugins, to IDE support and community.
For me, there's not a single reason to switch back to Maven. But don't take my word, do your own research and wonder why a big project like the Spring Framework moved from Maven to Gradle, or why Google chose Gadle over Maven :-)
