### ISSUE TITLE
The custom game table view is listing duplicates and not refreshing correctly

### ISSUE THREAD

**Issue by dev-nulled** [FAForever/downlords-faf-client#2132]
If you leave the 'play > custom games > table' view open for a length of time (hours?) you the game list does not update correctly.  You will see duplicates show up in the list and new games may or may not appear.

Clicking to tiles, then back to table refreshes the game list back to what it should be.  This was happening prior to the change where custom games is no longer the default view for play.

My suspicion is there is a timeout issue with these games that is jamming things up.  

Screenshots attached - the table view, clicking tiles, then immediately back to table view.  A few duplicate games - but also worth noting the list of games is very different.

![screen 0](https://user-images.githubusercontent.com/47699221/106363735-0164fa00-62f0-11eb-925b-d16484630181.png)
![screen 1](https://user-images.githubusercontent.com/47699221/106363740-09249e80-62f0-11eb-8c6b-3037cba935df.png)
![screen 2](https://user-images.githubusercontent.com/47699221/106363745-0d50bc00-62f0-11eb-9c80-72890442545b.png)

**Comment by dev-nulled** [comment]
![screen 4](https://user-images.githubusercontent.com/47699221/106369246-6121cc00-6315-11eb-935e-0a260b235a70.png)

Another shot after a few hours.

**Comment by Wizek** [comment]
I have also an issue to report that may very well be connected to this or have the same root cause: I often create servers, and they used to fill up rather quickly, sometimes in minutes, usually at most in 30 minutes.

Ever since 1.4.0 came out, they take agonizingly long to fill up, 1-2-3 hours sometimes, even when there is only one slot left from 12. I suspect this is because many players just don't see the game at all in their client.

I'm not sure if I should report this as a separate issue or if it is best to keep it here as a comment.

**Comment by dev-nulled** [comment]
@Brutus5000  Think I found the issue.  Will be doing a bit more testing to confirm.

**Comment by Sheikah45** [comment]
This is most likely an issue with the comparator for the rating range column
