### ISSUE TITLE
Alt tab changes d to deselect in chat tab

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/downlords-faf-client#2191]

**Comment by 1-alex98** [comment]
Probably a java fx thing

**Comment by 1-alex98** [comment]
I guess that is just the way it works. There is a mode where you toggle through the different controls. You know TAB gets you to the next control and so on. After alt tabing of course you loose focus on the input. Problematic would only be if after reselecting the iput that d stays "deselect" instead of the letter d ....

**Comment by MostLostNoob** [comment]
It seems that a workaround for this issue is to perform another Alt-Tab cycle to switch to another program & then back to the client. After the 2nd Alt-Tab cycle, the d key resumes working in the chat text box.

**Comment by BlackYps** [comment]
I think it has to do with the mnemonic parsing settings of the client. My guess is that it thinks the alt button is pressed. Maybe there is a way to disable mnemonic parsing altogether, because nobody uses that for the client anyway

**Comment by Marc-Spector** [comment]
I think it is possible to close this issue as the bug is no longer reproduced in the client version `2021.12.0`.

**Comment by Sheikah45** [comment]
This is no longer reproducible in the client 2021.12.0. Assuming a dependency update changed the behavior.
