### ISSUE TITLE
Improving error handling of expected errors

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#2366]
**Is your feature request related to a problem? Please describe.**
It creeps me out that we throw away expected exceptions and turn them into runtime exceptions showing them to the user in a "Uh oh, something went wrong we have no clue what" even if we exactly know what the problem was.

This is sort of the result of the relentless suppressing of checked exceptions all over the code.

Unfortunately our users are not capable of reading a stack trace and understanding it. We should try to wrap it into more useful error logs.

Examples:
- If there is a runtime exception related to the game process and an IO exception is flying we **know** the game has crashed. And we could catch this properly and point the the user to basic game fixes (e.g. turn of your mods, surround sound, ...)
- If on preparing the game to launch we encounter a AccessDeniedException we can tell the user that there was some issues with setting up the files and potential solutions (Check if game already running, restart pc, try to fix Windows permissions, deactive AV)
- LoginFailedException: Lost connection to server during login -> it already is a wrapped exception and just needs a nicer text
- ...

In cases were we do not catch the exception we could at least try to unwrap CompletionExceptions and remove one layer of exceptions to bring the user closer to the root cause.

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
Yes I agree have been slowly trying to move towards this.

For tracking:

With the loginFailed Exception those should actually be fixed by the lobby client now might need additionaly wrapping but have not seen what these errors are recently.

There is a wrapping process for the game crashing currently based off the exit code of the game log. We could add additional scanning of the game log to identify specific known issues.

AccessDeniedExceptions can give direct response of which files could not be accessed
