### ISSUE TITLE
Cancelling while matched results in a bug

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/downlords-faf-client#2607]
See https://forum.faforever.com/topic/3475/possible-cause-for-the-recurring-setting-up-automatch-cycle

**Comment by 1-alex98** [comment]
I think this is a rumour

**Comment by 1-alex98** [comment]
Today a had a game I wanted to join(10/12 players) and I connected forever. After cancelling trying to join other lobbies did not work, the client did not launch the game. It did update binaries and then nothing, no error no nothing(no game running in task manager). I relaunched the client and exactly the same happened. Relaunching the client and not trying to connect exactly that game made it work :D Sadly guy closed game before I launched the debugger... Joined about 100 other games to try to reproduce but cloud not find ppl I can not connect to, always works XD ...

Maybe sabotaging the connection cloud reproduce the issue. Cancelling before connecting does not seem to do it.

Overview over the logs:
 23:32:33.747 -> Started game 
 23:33:04.898 -> Terminated due to connection failure
 23:33:09.056 -> User retries joining game
 23:33:09.475 -> Client asks server to join game
 ->Notice here that the server should have send a game_launch message, which it never did 6 seconds should be more than enough. Other server messages are received.<-
 23:33:15.858 -> User gets nervous and reclicks
 23:33:16.270 -> Client informs server about intention to join
-> Missing game_launch message, this time way more time than 6 seconds <-
 23:33:43.914 -> User closes client as nothing happens
RELAUNCH
 23:34:21.756 -> User opens game that he can not connect to the 4th time
 23:34:23.463 -> Game starts
 23:34:45.126 -> Game closed because it did not connect
 23:34:48.907 -> User tries joining a different game than the one he is trying all the time
 23:34:49.349 -> Client informs server about join
 -> Missing game_launch message. Pattern repeats never a game_launch is received <-
 23:38:26.899 -> User restarts client
 23:48:59.763 -> Server does finally respond to the game_join and client launches game that connects. User now selects a completely different game, that is why it works potentially.
 23:49:55.214 -> Joining second game also no problem


[client2.log](https://github.com/FAForever/downlords-faf-client/files/8366777/client2.log)

This seems to be a server bug from the client log point of view. The game_launch is missing, why no idea 😮 . Maybe @Askaholic cloud get the server log of exactly that time and message sent. Not sure if that is actually an option and how hard that is.

**Comment by Sheikah45** [comment]
There have been some weird response times on grafana for the server as well recently. I have seen it jump to 200ms when normally it sits at 5ms.

**Comment by 1-alex98** [comment]
hmm I would not think that is related

**Comment by 1-alex98** [comment]
I mean it did not respond even if it was given way more than 6 seconds and in the other cases it responded immediately. After the  game_join, gam_info messages were still received anyways.

**Comment by 1-alex98** [comment]
Should we move this to the server repo just to show that we can probably not do anything about it 🤔

**Comment by Askaholic** [comment]
We can only get server logs if this happened recently since only a few hours of data is saved due to how the docker logging is currently configured. Not sure what the exact amount is.


The only reason that the game launch message might not get sent that I can think of would be if the user’s connection is not fast enough to receive all of the data from the server. Then the server may stop handling incoming messages from the client until the client has read a sufficient number of bytes (the write buffer is emptied on the server side). If the client can’t read bytes as fast as the server is writing them (due to lots of broadcasted messages for example) then the write buffer might not be fully emptied for a long time. But then reconnecting should fix this as the buffer is quite large.

**Comment by 1-alex98** [comment]
@Askaholic other server messages are read and logged. Also I am connected via cable and I have stable internet. I doubt that cloud have happened here.

**Comment by 1-alex98** [comment]
was less than 2 hours ago

**Comment by Askaholic** [comment]
Ok then I’ll request logs

**Comment by 1-alex98** [comment]
23:33:16.270 CEST

**Comment by Sheikah45** [comment]
So is this not something that can be handled in the client?

**Comment by 1-alex98** [comment]
we did not found what the actually problem is

**Comment by Sheikah45** [comment]
Unable to replicate
