### ISSUE TITLE
Pixel Aliasing on the Newshub tab

### ISSUE THREAD

**Issue by phongu** [FAForever/downlords-faf-client#2758]
**Describe the bug**
Images and text on the newshub have jagged edges, compared to when viewed in firefox browser.
**Screenshots**
see comment below https://github.com/FAForever/downlords-faf-client/issues/2758#issuecomment-1207184026

**Comment by Brutus5000** [comment]
Really strange as the client webview is based on Webkit just as Safari and Chrome

**Comment by phongu** [comment]
I've used other webkit implementations and have never seen this problem

**Comment by JaviTrek** [comment]
1920x1080 image downscaled in the new newshub
![image](https://user-images.githubusercontent.com/96269542/181291138-71e7e999-1ea4-49b9-91c9-d3305cdb0c3e.png)
![image](https://user-images.githubusercontent.com/96269542/181291175-8e328d41-182a-4898-a39a-9f667c2d80d4.png)

I'm not sure if maybe it has to do with how the current newshub works but in my updated version, the images look quite fine. Not sure if its due to that on the current newshub, alot of images are 145x97 or other very small dimensions where one pixel can be quite the difference. But it seems this isn't an issue in the new implementation of the newshub.

**Comment by phongu** [comment]
Javii also suggested on discord that using
`background-image: url()` instead of
`<img src="" />` to display the images might make the difference. I'm just leaving this comment here for future reference

**Comment by phongu** [comment]
well now the newshub update is public and i still see the issue

**Comment by phongu** [comment]
[website](https://media.discordapp.net/attachments/305398434993668098/1005407940515217408/unknown.png)
[client](https://media.discordapp.net/attachments/305398434993668098/1005407976858853447/unknown.png)

**Comment by phongu** [comment]
Plain HTML text is now aliased as well, in the screenshots above you can see the difference if you focus on the bold news titles

**Comment by phongu** [comment]
Eternal reports that Microsoft Edge webview2 sees the above content like this: [image](https://media.discordapp.net/attachments/305398434993668098/1005454715141767248/unknown.png)

The text is antialiased but the images are not

**Comment by phongu** [comment]
it's a known bug in microsoft edge apparently https://stackoverflow.com/questions/47443161/pixelated-image-downscaling-in-microsoft-edge
