### ISSUE TITLE
Use AppData\Roaming folder instead of ProgramData as default Data Location

### ISSUE THREAD

**Issue by vladislemon** [FAForever/downlords-faf-client#2789]
Pros:
- No mess with access permissions
- No warning about ProgramData if running as admin
- No space use of C: drive if users folder moved to another drive

Cons:
- Data will not be shared between multiple users on same system

Or maybe we should use %user%/.faforever as on linux?

**Comment by Sheikah45** [comment]
Users can change the data location to whatever folder they want in settings.

Also folders under the user directory are specifically avoided as default locations because not all characters play nicely with SCFA. Moving the default to under the User path would cause more start up headaches for players who have Cyrillic characters in their username.

Also some older mods expect some data to be in program data so it works for backwards compatibility.

**Comment by vladislemon** [comment]
@Sheikah45
Seems reasonable. I guess my setup is somehow rare (disabled UAC, users folder on separate drive).
Ok, maybe I should consider to maintain those changes only in fork.
Thank you for the clarification.
