### ISSUE TITLE
Duplicates in custom games list

### ISSUE THREAD

**Issue by Jazzic** [FAForever/downlords-faf-client#2910]
**Describe the bug**
The same game is listed several times. 

**To Reproduce**
The problem most often occurs after a while, but does also show up immediately when then client is opened.

**Log or error message**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/9013575/216723378-c547e689-37fa-4260-9a75-1e00a7c222d6.png)

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Askaholic** [comment]
That’s probably just someone rehosting the game, you can see that the number of players is different so it’s not a duplicate display of the same game. Probably one of them is not joinable if you try to join and will disappear after a few minutes. This is due to the fact that there are ways for the game to be closed without the server knowing about it, but it should be cleaned up after a few minutes.

**Comment by Jazzic** [comment]
Not acknowledgeing a bug, does not make it go away.  Here is another screenshot with the same game, but with different hosts. In this situation, chif_107 did not host a game.
![image](https://user-images.githubusercontent.com/9013575/219328763-3a4400b5-5da7-4306-be3e-ae8ace905242.png)

**Comment by Jazzic** [comment]
Not acknowledgeing a bug, does not make it go away. Here is another screenshot with the same game, but with different hosts. In this situation, chif_107 did not host a game.
![image](https://user-images.githubusercontent.com/9013575/219329485-71a95611-9b1d-4920-b2e9-39404202fecb.png)

**Comment by Askaholic** [comment]
Have you tried joining the games?

**Comment by Sheikah45** [comment]
Should be fixed by the recent game update backend rework
