### ISSUE TITLE
[Feature]: 6v6 ladder exclusively for GAP

### ISSUE THREAD

**Issue by mrchris2000** [FAForever/downlords-faf-client#3220]
### Is your feature request related to a problem?

This is a suggestion to simplify match balancing for GAP addicts.

### Describe the solution you'd like

Add a ladder option exclusively for GAP so that games can fill with roughly equivalently balanced teams - takes the hassle out of balancing a custom gap.

With GAP being clearly a preferred map for much of the player base, a dedicated means of getting a balanced match might speed up the lobby sim a bit?

### Describe alternatives you've considered

Other map specific dedicated ladders for Astro, Canis and Setons perhaps... but that could quickly get cluttered.

**Comment by Brutus5000** [comment]
Let's put aside the question whether or not we want a dualgap or astro matchmaker at all.

Just because FAF supports 6v6 technically, doesn't mean we recommend on using.
6v6 is inherently unstable with our current connectivity. Adding it as an "official" would require it to be mostly stable though. The custom lobby has the advantage that it can filter out some portions of connection problems before the game starts. The matchmaker logic cannot do this. The majority of games would probably be stuck in the game launching screen forever.
