### ISSUE TITLE
Set some kind of min size for the stage

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#444]
![error](https://cloud.githubusercontent.com/assets/19996713/21271350/f80edfc6-c3ba-11e6-97f8-22c3ba8b7932.png)

**Comment by axel1200** [comment]
![grafik](https://cloud.githubusercontent.com/assets/19996713/22067495/ccbcbe10-dd91-11e6-9479-c2fba45f3cbb.png)

**Comment by Bearnn** [comment]
Thought I'd have a look at this: 

In the faforever/client/fx/WindowController.java there is this paragraph of code under the onWindowResize(MouseEvent event) method:

 if (newHeight < stage.getMinHeight()) {
      newHeight = stage.getMinHeight();
    }
    if (newWidth < stage.getMinWidth()) {
      newWidth = stage.getMinWidth();
    }

However I can't find anywhere where the setMinWidth and setMinHeight is used. Maybe I'm just not searching the code properly but thought I'd mention it.

Any advice would be appreciated!

**Comment by micheljung** [comment]
[`main.fxml`](https://github.com/FAForever/downlords-faf-client/blob/develop/src/main/resources/theme/main.fxml) has `minHeight` and `minWidth` set, but the stage (=window) was allowed to be smaller than that. The pane of `main.fxml` then just got "cropped" instead of getting shrinked. This is why I added the code above (which, btw, I reformatted using ```)

Not sure why it isn't working, and not sure if it's really a beginner task then.. :)

**Comment by micheljung** [comment]
I don't like applications that prevent me to resize them as I like. If that's what the user wants, he should be able to do it.
