### ISSUE TITLE
Add functionality to "feedback" and "support"

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#497]
![grafik](https://cloud.githubusercontent.com/assets/19996713/22803951/46aa7064-ef17-11e6-886a-7fd76084a6e4.png)

- [ ] decide what support should do
- [ ] decide what feedback should do

**Comment by axel1200** [comment]
Maybe 
redirect to tec support 
some form that can be filled out and send to an moderator

**Comment by axel1200** [comment]
We could have the button "help" and on click we open a new window, with an info text, which contains things like:
-When do I contact tec support.
-What should I do before contacting tec support(like restart etc.).
-U should provide a detailed description etc.

Maybe be could also Link our GutHub issues and make clear guide lines like:
-When shell i craete an issue...
-If it is reproducable
-If it is a client bug and not in game error
-Only after reinstalling or so
-Provide Screenshots and a clear description
-If u looked through and made sure if that issues does not exist already

And maybe force the user to read the text by enabling the buttons(to tec support and GitHub) only after like a minute

**Comment by CrazyTim** [comment]
Hi, speaking from experience: that seems a bit full-on to me. You'll be lucky if anyone has the patience to submit a bug that way.

I would be careful about a form, because it implies that someone will respond and support the user, and then you need someone to man the post and reply and interpret issues.

As this is open source project, for support I would redirect the user to github, and show them those instructions to help them raise the issue in github. Keep it all in one place.

A feedback button sounds good, but again, who is going to be responsible to interpret all the feedback. Again I would make it easier on the devs and direct issues to github, and general chat/feedback to the slack group.

**Comment by themasch** [comment]
Sentry has a user feedback feature: https://docs.sentry.io/learn/user-feedback/
The default way is showing a html page which uses js to show the form but there should a (easy) way to implement it in java, too. When #351 is implemented, we could also get more context on reported errors using this way.

**Comment by Sheikah45** [comment]
Will just remove the feedback button as nothing has been thought of
