### ISSUE TITLE
Rating distribution in 1v1

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/downlords-faf-client#558]
So clicking on 1v1 ranked match tab shows this for rating distribution
Not saying too much
![downlords-faf-client_2017-06-26_12-10-04](https://user-images.githubusercontent.com/10947024/27534850-9b6519c6-5a68-11e7-9961-5ea9377ae32b.png)

**Comment by NiklasKopp** [comment]
Cannot reproduce. This is how it currently looks on develop running it with prod configuration:

![image](https://user-images.githubusercontent.com/15572250/30750073-baad1d8c-9fb5-11e7-94ad-03f56fc51158.png)

Looks fine to me.

I would personally prefer ordering by score, so that the positive scores aren't mixed with the negative ones, which would yield the following:

![image](https://user-images.githubusercontent.com/15572250/30750854-daae56f8-9fb7-11e7-8d38-b8e395d95dd3.png)

If you guys like the second version better I could file a pull request for it, it's just a simple one line change. Not sure if that's in the scope of this issue though.

**Comment by Androish** [comment]
Might be better to remove the 0 rank? I am assuming the reason it is so big is that anyone who has no ranked games ends up with that? That being so large "hides" the other scores.

Hmm better idea, not hide it but only show the rating distribution for players that has had more than X(maybe 10?) games.

I Agree the 2nd one is better looking

**Comment by speed2CZ** [comment]
Hiding the 0 rank was the idea. no one cares how many ppl havent played a game yet

**Comment by NiklasKopp** [comment]
This is the result hiding all with fewer than 10 played games. There are some 0 rated players in there, so rank 0 does not mean no games played

![image](https://user-images.githubusercontent.com/15572250/30751840-df95b3c0-9fba-11e7-8d23-53debfc3e34d.png)

**Comment by Androish** [comment]
That looks alot better! :) I guess it might need a small text saying that it is for more than x games

**Comment by NiklasKopp** [comment]
Text is added (en + de)

Might even work with 5 instead of 10

![image](https://user-images.githubusercontent.com/15572250/30752498-bed32a44-9fbc-11e7-8d30-d0196f181854.png)

**Comment by speed2CZ** [comment]
10 games looks better

**Comment by OCGDFS** [comment]
Are the 1v1 games counted as "games played", or global games, or all? because there is still a big deviation from the normal distribution for 0rating/10games.

**Comment by OCGDFS** [comment]
are the 10+ games ladder games, or games in general? I have the suspicion that players who just dont play ladder are also included in that calculation, regarding the big deviation from the normal distribution for players with 0 rating.
