### ISSUE TITLE
Error in Online Replay Vault

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#581]
When searching for online replays and finding one that has a review on the map, the client shows an error. Reason for that is that in the Api call mapVersion.reviews are not included, but parsed resulting in a null Pointer exception!

**Comment by axel1200** [comment]
In general we should think about null checks in the parsing of dtos.

**Comment by micheljung** [comment]
Whenever we get a NPE, apparently we need that content. What would you do if you see that something is `null`, not do what you wanted to?

It highly depends on the specific use case, but in general, let exceptions fly when there is an error in the program. Some programmers tend to program "defensively" like so:

```
public String readFile(Path file) {
  if(file == null || !Files.exists(file)) {
    return null; // Or ""
  }
  return /* code that can throw NPE */
}
```
but that's bad because either now the caller gets an NPE and tracing the actual cause becomes more difficult, or the caller gets an empty string and doesn't realize that he passed null into the method, or that the file doesn't exist. [Need Robust Software? Make It Fragile](http://www.yegor256.com/2015/08/25/fail-fast.html).

But I'm not sure if that's what you meant :)

**Comment by axel1200** [comment]
Did we really fix that?

**Comment by axel1200** [comment]
Yeah we did
