### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by Cheyans** [FAForever/downlords-faf-client#63]
I feel like this would be a good addition

**Comment by tatsujb** [comment]
OMG yes !! I was just thinking about telling this to sheeo yesterday, but if we can manage it on our own client it would be even better.

**Comment by Cheyans** [comment]
I feel like it wont be hard because the only thing we have to do really is incorporate a way to launch games with featured mods as all other mods should be accessible by the in game lobby. For coop it will probably be a lot more complex/

**Comment by tatsujb** [comment]
offline it'll just be so that certain tabs are off such as the ladder rankings and vaults. dissalowing you to have the ui to download things.

discovering lan games will be quite a nifty trick though. I donot know what sort of service this requires to be running. 

maybe we simply mimic the behavior of the server on the hostee's side?

**Comment by 1-alex98** [comment]
You can execute the exe and that is offline mode basically 🤔 no?

**Comment by Sheikah45** [comment]
True but it is just not very user friendly

**Comment by 1-alex98** [comment]
Yes maybe a button launching the exe on the log in screen

**Comment by Sheikah45** [comment]
I think that would be sufficient for offline mode then could also get rid of all the MockServices. I was thinking if there was a mode that just didn't have you login in to the server. And then just improve the error handling for the api.

**Comment by Sheikah45** [comment]
Button on login window added already
