### ISSUE TITLE
Show the faction of a player in the replay detail

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#742]
The icons are already in our ico moon font ;)
@20seven interested?

**Comment by andreasley** [comment]
This was also mentioned in https://github.com/FAForever/downlords-faf-client/issues/1645, added in https://github.com/FAForever/downlords-faf-client/pull/1646 and released in 1.1.5, but unfortunately, the wrong factions are being shown.

Instead of Cybran, UEF is shown
Instead of Aeon, Cybran is shown
Instead of UEF, Aeon is shown

**Comment by 1-alex98** [comment]
We know I think it is ether fixed or there is a PR for it
