### ISSUE TITLE
Smart live replays

### ISSUE THREAD

**Issue by Cheyans** [FAForever/downlords-faf-client#82]
if the game uid resolved from live replay link is not in the list of current game info beans, then launch the replay from the replay vault.

**Comment by Cheyans** [comment]
Use cases:
<ol>
 <li>Game has been running for 5 minutes -> launch live replay </li>
 <li>Game has not been running for 5 minutes -> immediate notification "Game is not watchable yet, wait X seconds" </li>
 <li>Game has finished and a live replay link was posted in aeolus -> launch from replay vault </li>
 <li>Player is not in game anymore, but still reported by server (I think I fixed this client side, I have to double check though) -> launch replay through a different player </li>
</ol>

**Comment by axel1200** [comment]
@micheljung did u not do this?

**Comment by micheljung** [comment]
No, the client doesn't wait yet. Only the button in the replay vault has a countdown of 5min. I'd like to update it so that all "watch replay" buttons have this countdown and are always clickable. When you click before the countdown reaches 0, the client should inform you about the situation and ask whether you want to start it as soon as it's ready.

If the user says yes, a background task should be submitted which will then display in the status bar: "Starting live replay in <time>" and launch it as soon as it's ready.
